# Custom shortcuts for splitting panes
bind s split-window -h
bind v split-window -v

# Navigate between panes with h, j, k, l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Number windows from 1
set -g base-index 1

# (Optional) Enable mouse support for resizing panes
set -g mouse on

# Enable the feature (on | off | always)
# 'always' (tmux 3.3+) forces it even if the app doesn't ask for it
set -s extended-keys on
set -g extended-keys-format csi-u

# Ensure your terminal is recognized as supporting it
set -as terminal-features 'xterm*:extkeys'
